all:
  hosts:
    my_router:
      ansible_host: 192.168.1.239
      ansible_user: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/network/my_router field=ansible_user') }}"
      ansible_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/network/my_router field=ansible_password') }}"
      ansible_become_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/network/my_router field=ansible_become_password') }}"
      ansible_connection: network_cli
      ansible_network_os: ios